#!/bin/zsh




#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# exec wmaker
# exec icewm
# exec blackbox
# exec fluxbox
# exec openbox-session
# exec cinnamon-session
# ...or the Window Manager of your choice

#solarize everything!
#exec [[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources &

#[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
xrdb -merge ~/.Xresources

#exec ssh -n -X -C bart@2.2.2.2 /usr/bin/i3 -c ~/.config/i3/config
exec ssh -n -X -C bart@2.2.2.2 i3

#for now, half the work is being done in ~/.i3/config
#export NSM_URL=osc.udp://WheezyOne.lbb:17552
#exec nsmd --osc-port 17552



#exec i3



