#!/bin/zsh -f

NAME=$0:t
wmiir remove /rbar/$NAME &>/dev/null
echo | wmiir create /rbar/$NAME

while (wmiir read /ctl &>/dev/null) {
	wmiir xwrite /rbar/$NAME $(df | awk 'BEGIN { printf("hd "); } /^\/dev\// { printf("%s=%s ", $6, $5) }')
	sleep 1m
}
